// Code generated by ogen, DO NOT EDIT.

package traqapi

import (
	"net/http"

	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenregex"
)

var regexMap = map[string]ogenregex.Regexp{
	"^([a-zA-Z0-9_-]{1,32}|Webhook#[a-zA-Z0-9_-]{22})$": ogenregex.MustCompile("^([a-zA-Z0-9_-]{1,32}|Webhook#[a-zA-Z0-9_-]{22})$"),
	"^(\\/[a-zA-Z0-9-_]+)+$":                            ogenregex.MustCompile("^(\\/[a-zA-Z0-9-_]+)+$"),
	"^[\\x20-\\x7E]{10,32}$":                            ogenregex.MustCompile("^[\\x20-\\x7E]{10,32}$"),
	"^[a-zA-Z0-9-_]{1,20}$":                             ogenregex.MustCompile("^[a-zA-Z0-9-_]{1,20}$"),
	"^[a-zA-Z0-9_-]{1,16}$":                             ogenregex.MustCompile("^[a-zA-Z0-9_-]{1,16}$"),
	"^[a-zA-Z0-9_-]{1,32}$":                             ogenregex.MustCompile("^[a-zA-Z0-9_-]{1,32}$"),
	"^[a-zA-Z0-9_]{0,15}$":                              ogenregex.MustCompile("^[a-zA-Z0-9_]{0,15}$"),
	"^[a-zA-Z0-9_]{1,15}$":                              ogenregex.MustCompile("^[a-zA-Z0-9_]{1,15}$"),
}

type (
	optionFunc[C any] func(*C)
)

type clientConfig struct {
	Client ht.Client
}

// ClientOption is client config option.
type ClientOption interface {
	applyClient(*clientConfig)
}

var _ ClientOption = (optionFunc[clientConfig])(nil)

func (o optionFunc[C]) applyClient(c *C) {
	o(c)
}

func newClientConfig(opts ...ClientOption) clientConfig {
	cfg := clientConfig{
		Client: http.DefaultClient,
	}
	for _, opt := range opts {
		opt.applyClient(&cfg)
	}
	return cfg
}

type baseClient struct {
	cfg clientConfig
}

func (cfg clientConfig) baseClient() (c baseClient, err error) {
	c = baseClient{cfg: cfg}
	return c, nil
}

// Option is config option.
type Option interface {
	ClientOption
}

// WithClient specifies http client to use.
func WithClient(client ht.Client) ClientOption {
	return optionFunc[clientConfig](func(cfg *clientConfig) {
		if client != nil {
			cfg.Client = client
		}
	})
}
