// Code generated by ogen, DO NOT EDIT.
package traqapi

type ActivateBotRes interface {
	activateBotRes()
}

type AddMessageStampRes interface {
	addMessageStampRes()
}

type AddMyStarRes interface {
	addMyStarRes()
}

type AddMyUserTagRes interface {
	addMyUserTagRes()
}

type AddUserGroupAdminRes interface {
	addUserGroupAdminRes()
}

type AddUserGroupMemberRes interface {
	addUserGroupMemberRes()
}

type AddUserTagRes interface {
	addUserTagRes()
}

type ChangeMyNotifyCitationRes interface {
	changeMyNotifyCitationRes()
}

type ChangeMyPasswordRes interface {
	changeMyPasswordRes()
}

type ChangeParticipantRoleRes interface {
	changeParticipantRoleRes()
}

type ChangeStampImageRes interface {
	changeStampImageRes()
}

type ChangeUserPasswordRes interface {
	changeUserPasswordRes()
}

type ClipMessageRes interface {
	clipMessageRes()
}

type CreateBotRes interface {
	createBotRes()
}

type CreateChannelRes interface {
	createChannelRes()
}

type CreateClientRes interface {
	createClientRes()
}

type CreateClipFolderRes interface {
	createClipFolderRes()
}

type CreatePinRes interface {
	createPinRes()
}

type CreateStampPaletteRes interface {
	createStampPaletteRes()
}

type CreateUserGroupRes interface {
	createUserGroupRes()
}

type CreateUserRes interface {
	createUserRes()
}

type CreateWebhookRes interface {
	createWebhookRes()
}

type DeleteBotRes interface {
	deleteBotRes()
}

type DeleteClientRes interface {
	deleteClientRes()
}

type DeleteClipFolderRes interface {
	deleteClipFolderRes()
}

type DeleteFileRes interface {
	deleteFileRes()
}

type DeleteMessageRes interface {
	deleteMessageRes()
}

type DeleteOgpCacheRes interface {
	deleteOgpCacheRes()
}

type DeleteStampPaletteRes interface {
	deleteStampPaletteRes()
}

type DeleteStampRes interface {
	deleteStampRes()
}

type DeleteUserGroupRes interface {
	deleteUserGroupRes()
}

type DeleteWebhookMessageRes interface {
	deleteWebhookMessageRes()
}

type DeleteWebhookRes interface {
	deleteWebhookRes()
}

type EditBotRes interface {
	editBotRes()
}

type EditChannelRes interface {
	editChannelRes()
}

type EditChannelSubscribersRes interface {
	editChannelSubscribersRes()
}

type EditChannelTopicRes interface {
	editChannelTopicRes()
}

type EditClientRes interface {
	editClientRes()
}

type EditClipFolderRes interface {
	editClipFolderRes()
}

type EditMeRes interface {
	editMeRes()
}

type EditMessageRes interface {
	editMessageRes()
}

type EditMyUserTagRes interface {
	editMyUserTagRes()
}

type EditStampPaletteRes interface {
	editStampPaletteRes()
}

type EditStampRes interface {
	editStampRes()
}

type EditUserGroupMemberRes interface {
	editUserGroupMemberRes()
}

type EditUserGroupRes interface {
	editUserGroupRes()
}

type EditUserRes interface {
	editUserRes()
}

type EditUserTagRes interface {
	editUserTagRes()
}

type EditWebhookRes interface {
	editWebhookRes()
}

type GetActivityTimelineRes interface {
	getActivityTimelineRes()
}

type GetBotIconRes interface {
	getBotIconRes()
}

type GetBotLogsRes interface {
	getBotLogsRes()
}

type GetBotRes interface {
	getBotRes()
}

type GetChannelBotsRes interface {
	getChannelBotsRes()
}

type GetChannelPathRes interface {
	getChannelPathRes()
}

type GetChannelPinsRes interface {
	getChannelPinsRes()
}

type GetChannelRes interface {
	getChannelRes()
}

type GetChannelStatsRes interface {
	getChannelStatsRes()
}

type GetChannelSubscribersRes interface {
	getChannelSubscribersRes()
}

type GetChannelTopicRes interface {
	getChannelTopicRes()
}

type GetChannelViewersRes interface {
	getChannelViewersRes()
}

type GetClientRes interface {
	getClientRes()
}

type GetClipFolderRes interface {
	getClipFolderRes()
}

type GetClipsRes interface {
	getClipsRes()
}

type GetDirectMessagesRes interface {
	getDirectMessagesRes()
}

type GetFileMetaRes interface {
	getFileMetaRes()
}

type GetFileRes interface {
	getFileRes()
}

type GetFilesRes interface {
	getFilesRes()
}

type GetLiveKitTokenRes interface {
	getLiveKitTokenRes()
}

type GetMessageClipsRes interface {
	getMessageClipsRes()
}

type GetMessageRes interface {
	getMessageRes()
}

type GetMessageStampsRes interface {
	getMessageStampsRes()
}

type GetMessagesRes interface {
	getMessagesRes()
}

type GetMyIconRes interface {
	getMyIconRes()
}

type GetMyQRCodeRes interface {
	getMyQRCodeRes()
}

type GetOAuth2AuthorizeRes interface {
	getOAuth2AuthorizeRes()
}

type GetOgpRes interface {
	getOgpRes()
}

type GetPinRes interface {
	getPinRes()
}

type GetPublicUserIconRes interface {
	getPublicUserIconRes()
}

type GetQallEndpointsRes interface {
	getQallEndpointsRes()
}

type GetRoomMetadataRes interface {
	getRoomMetadataRes()
}

type GetRoomsRes interface {
	getRoomsRes()
}

type GetSoundboardListRes interface {
	getSoundboardListRes()
}

type GetStampImageRes interface {
	getStampImageRes()
}

type GetStampPaletteRes interface {
	getStampPaletteRes()
}

type GetStampRes interface {
	getStampRes()
}

type GetStampStatsRes interface {
	getStampStatsRes()
}

type GetTagRes interface {
	getTagRes()
}

type GetThumbnailImageRes interface {
	getThumbnailImageRes()
}

type GetUserDMChannelRes interface {
	getUserDMChannelRes()
}

type GetUserGroupAdminsRes interface {
	getUserGroupAdminsRes()
}

type GetUserGroupMembersRes interface {
	getUserGroupMembersRes()
}

type GetUserGroupRes interface {
	getUserGroupRes()
}

type GetUserIconRes interface {
	getUserIconRes()
}

type GetUserRes interface {
	getUserRes()
}

type GetUserStatsRes interface {
	getUserStatsRes()
}

type GetUserTagsRes interface {
	getUserTagsRes()
}

type GetUsersRes interface {
	getUsersRes()
}

type GetWebhookIconRes interface {
	getWebhookIconRes()
}

type GetWebhookMessagesRes interface {
	getWebhookMessagesRes()
}

type GetWebhookRes interface {
	getWebhookRes()
}

type InactivateBotRes interface {
	inactivateBotRes()
}

type LetBotJoinChannelRes interface {
	letBotJoinChannelRes()
}

type LetBotLeaveChannelRes interface {
	letBotLeaveChannelRes()
}

type LinkExternalAccountRes interface {
	linkExternalAccountRes()
}

type LoginRes interface {
	loginRes()
}

type LogoutRes interface {
	logoutRes()
}

type PostDirectMessageRes interface {
	postDirectMessageRes()
}

type PostFileRes interface {
	postFileRes()
}

type PostMessageRes interface {
	postMessageRes()
}

type PostOAuth2AuthorizeDecideRes interface {
	postOAuth2AuthorizeDecideRes()
}

type PostOAuth2AuthorizeRes interface {
	postOAuth2AuthorizeRes()
}

type PostOAuth2TokenRes interface {
	postOAuth2TokenRes()
}

type PostSoundboardPlayRes interface {
	postSoundboardPlayRes()
}

type PostSoundboardRes interface {
	postSoundboardRes()
}

type PostWebRTCAuthenticateRes interface {
	postWebRTCAuthenticateRes()
}

type PostWebhookRes interface {
	postWebhookRes()
}

type RegisterFCMDeviceRes interface {
	registerFCMDeviceRes()
}

type ReissueBotRes interface {
	reissueBotRes()
}

type RemoveMessageStampRes interface {
	removeMessageStampRes()
}

type RemoveMyUserTagRes interface {
	removeMyUserTagRes()
}

type RemovePinRes interface {
	removePinRes()
}

type RemoveUserGroupAdminRes interface {
	removeUserGroupAdminRes()
}

type RemoveUserGroupMemberRes interface {
	removeUserGroupMemberRes()
}

type RemoveUserGroupMembersRes interface {
	removeUserGroupMembersRes()
}

type RemoveUserTagRes interface {
	removeUserTagRes()
}

type RevokeClientTokensRes interface {
	revokeClientTokensRes()
}

type RevokeMyTokenRes interface {
	revokeMyTokenRes()
}

type SearchMessagesRes interface {
	searchMessagesRes()
}

type SetChannelSubscribeLevelRes interface {
	setChannelSubscribeLevelRes()
}

type SetChannelSubscribersRes interface {
	setChannelSubscribersRes()
}

type UnclipMessageRes interface {
	unclipMessageRes()
}

type UnlinkExternalAccountRes interface {
	unlinkExternalAccountRes()
}

type UpdateRoomMetadataRes interface {
	updateRoomMetadataRes()
}
