// Code generated by ogen, DO NOT EDIT.

package traqapi

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// OAuth2 provides OAuth2 security value.
	OAuth2(ctx context.Context, operationName OperationName) (OAuth2, error)
	// BearerAuth provides bearerAuth security value.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
}

func (s *Client) securityOAuth2(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.OAuth2(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"OAuth2\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
