// Code generated by ogen, DO NOT EDIT.

package traqapi

// setDefaults set default value of fields.
func (s *PostClientRequest) setDefaults() {
	{
		val := bool(false)
		s.Confidential.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PostMessageRequest) setDefaults() {
	{
		val := bool(false)
		s.Embed.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ThumbnailInfo) setDefaults() {
	{
		val := ThumbnailType("image")
		s.Type = val
	}
}
