// Code generated by ogen, DO NOT EDIT.

package traqapi

import (
	"github.com/google/uuid"
)

// ActivateBotParams is parameters of activateBot operation.
type ActivateBotParams struct {
	// BOTUUID.
	BotId uuid.UUID
}

// AddMessageStampParams is parameters of addMessageStamp operation.
type AddMessageStampParams struct {
	// メッセージUUID.
	MessageId uuid.UUID
	// スタンプUUID.
	StampId uuid.UUID
}

// AddUserGroupAdminParams is parameters of addUserGroupAdmin operation.
type AddUserGroupAdminParams struct {
	// ユーザーグループUUID.
	GroupId uuid.UUID
}

// AddUserGroupMemberParams is parameters of addUserGroupMember operation.
type AddUserGroupMemberParams struct {
	// ユーザーグループUUID.
	GroupId uuid.UUID
}

// AddUserTagParams is parameters of addUserTag operation.
type AddUserTagParams struct {
	// ユーザーUUID.
	UserId uuid.UUID
}

// ChangeParticipantRoleParams is parameters of changeParticipantRole operation.
type ChangeParticipantRoleParams struct {
	// ルームUUID.
	RoomId uuid.UUID
}

// ChangeStampImageParams is parameters of changeStampImage operation.
type ChangeStampImageParams struct {
	// スタンプUUID.
	StampId uuid.UUID
}

// ChangeUserPasswordParams is parameters of changeUserPassword operation.
type ChangeUserPasswordParams struct {
	// ユーザーUUID.
	UserId uuid.UUID
}

// ClipMessageParams is parameters of clipMessage operation.
type ClipMessageParams struct {
	// クリップフォルダUUID.
	FolderId uuid.UUID
}

// CreatePinParams is parameters of createPin operation.
type CreatePinParams struct {
	// メッセージUUID.
	MessageId uuid.UUID
}

// DeleteBotParams is parameters of deleteBot operation.
type DeleteBotParams struct {
	// BOTUUID.
	BotId uuid.UUID
}

// DeleteClientParams is parameters of deleteClient operation.
type DeleteClientParams struct {
	// OAuth2クライアントUUID.
	ClientId string
}

// DeleteClipFolderParams is parameters of deleteClipFolder operation.
type DeleteClipFolderParams struct {
	// クリップフォルダUUID.
	FolderId uuid.UUID
}

// DeleteFileParams is parameters of deleteFile operation.
type DeleteFileParams struct {
	// ファイルUUID.
	FileId uuid.UUID
}

// DeleteMessageParams is parameters of deleteMessage operation.
type DeleteMessageParams struct {
	// メッセージUUID.
	MessageId uuid.UUID
}

// DeleteOgpCacheParams is parameters of deleteOgpCache operation.
type DeleteOgpCacheParams struct {
	// OGPのキャッシュを削除したいURL.
	URL string
}

// DeleteStampParams is parameters of deleteStamp operation.
type DeleteStampParams struct {
	// スタンプUUID.
	StampId uuid.UUID
}

// DeleteStampPaletteParams is parameters of deleteStampPalette operation.
type DeleteStampPaletteParams struct {
	// スタンプパレットUUID.
	PaletteId uuid.UUID
}

// DeleteUserGroupParams is parameters of deleteUserGroup operation.
type DeleteUserGroupParams struct {
	// ユーザーグループUUID.
	GroupId uuid.UUID
}

// DeleteWebhookParams is parameters of deleteWebhook operation.
type DeleteWebhookParams struct {
	// WebhookUUID.
	WebhookId uuid.UUID
}

// DeleteWebhookMessageParams is parameters of DeleteWebhookMessage operation.
type DeleteWebhookMessageParams struct {
	// WebhookUUID.
	WebhookId uuid.UUID
	// メッセージUUID.
	MessageId uuid.UUID
}

// EditBotParams is parameters of editBot operation.
type EditBotParams struct {
	// BOTUUID.
	BotId uuid.UUID
}

// EditChannelParams is parameters of editChannel operation.
type EditChannelParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// EditChannelSubscribersParams is parameters of editChannelSubscribers operation.
type EditChannelSubscribersParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// EditChannelTopicParams is parameters of editChannelTopic operation.
type EditChannelTopicParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// EditClientParams is parameters of editClient operation.
type EditClientParams struct {
	// OAuth2クライアントUUID.
	ClientId string
}

// EditClipFolderParams is parameters of editClipFolder operation.
type EditClipFolderParams struct {
	// クリップフォルダUUID.
	FolderId uuid.UUID
}

// EditMessageParams is parameters of editMessage operation.
type EditMessageParams struct {
	// メッセージUUID.
	MessageId uuid.UUID
}

// EditMyUserTagParams is parameters of editMyUserTag operation.
type EditMyUserTagParams struct {
	// タグUUID.
	TagId uuid.UUID
}

// EditStampParams is parameters of editStamp operation.
type EditStampParams struct {
	// スタンプUUID.
	StampId uuid.UUID
}

// EditStampPaletteParams is parameters of editStampPalette operation.
type EditStampPaletteParams struct {
	// スタンプパレットUUID.
	PaletteId uuid.UUID
}

// EditUserParams is parameters of editUser operation.
type EditUserParams struct {
	// ユーザーUUID.
	UserId uuid.UUID
}

// EditUserGroupParams is parameters of editUserGroup operation.
type EditUserGroupParams struct {
	// ユーザーグループUUID.
	GroupId uuid.UUID
}

// EditUserGroupMemberParams is parameters of editUserGroupMember operation.
type EditUserGroupMemberParams struct {
	// ユーザーグループUUID.
	GroupId uuid.UUID
	// ユーザーUUID.
	UserId uuid.UUID
}

// EditUserTagParams is parameters of editUserTag operation.
type EditUserTagParams struct {
	// ユーザーUUID.
	UserId uuid.UUID
	// タグUUID.
	TagId uuid.UUID
}

// EditWebhookParams is parameters of editWebhook operation.
type EditWebhookParams struct {
	// WebhookUUID.
	WebhookId uuid.UUID
}

// GetActivityTimelineParams is parameters of getActivityTimeline operation.
type GetActivityTimelineParams struct {
	// 取得する件数.
	Limit OptInt `json:",omitempty,omitzero"`
	// 全てのチャンネルのタイムラインを取得する.
	All OptBool `json:",omitempty,omitzero"`
	// 同じチャンネルのメッセージは最新のもののみ取得するか.
	PerChannel OptBool `json:",omitempty,omitzero"`
}

// GetBotParams is parameters of getBot operation.
type GetBotParams struct {
	// 詳細情報を含めるかどうか.
	Detail OptBool `json:",omitempty,omitzero"`
	// BOTUUID.
	BotId uuid.UUID
}

// GetBotIconParams is parameters of getBotIcon operation.
type GetBotIconParams struct {
	// BOTUUID.
	BotId uuid.UUID
}

// GetBotLogsParams is parameters of getBotLogs operation.
type GetBotLogsParams struct {
	// 取得する件数.
	Limit OptInt `json:",omitempty,omitzero"`
	// 取得するオフセット.
	Offset OptInt `json:",omitempty,omitzero"`
	// BOTUUID.
	BotId uuid.UUID
}

// GetBotsParams is parameters of getBots operation.
type GetBotsParams struct {
	// 全てのBOTを取得するかどうか.
	All OptBool `json:",omitempty,omitzero"`
}

// GetChannelParams is parameters of getChannel operation.
type GetChannelParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// GetChannelBotsParams is parameters of getChannelBots operation.
type GetChannelBotsParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// GetChannelPathParams is parameters of getChannelPath operation.
type GetChannelPathParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// GetChannelPinsParams is parameters of getChannelPins operation.
type GetChannelPinsParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// GetChannelStatsParams is parameters of getChannelStats operation.
type GetChannelStatsParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
	// 削除されたメッセージを除外するかどうか(デフォルト false).
	ExcludeDeletedMessages OptBool `json:",omitempty,omitzero"`
}

// GetChannelSubscribersParams is parameters of getChannelSubscribers operation.
type GetChannelSubscribersParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// GetChannelTopicParams is parameters of getChannelTopic operation.
type GetChannelTopicParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// GetChannelViewersParams is parameters of getChannelViewers operation.
type GetChannelViewersParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// GetChannelsParams is parameters of getChannels operation.
type GetChannelsParams struct {
	// ダイレクトメッセージチャンネルをレスポンスに含めるかどうか.
	IncludeDm OptBool `json:",omitempty,omitzero"`
	// パスが一致するチャンネルのみを取得する.
	Path OptString `json:",omitempty,omitzero"`
}

// GetClientParams is parameters of getClient operation.
type GetClientParams struct {
	// 詳細情報を含めるかどうか.
	Detail OptBool `json:",omitempty,omitzero"`
	// OAuth2クライアントUUID.
	ClientId string
}

// GetClientsParams is parameters of getClients operation.
type GetClientsParams struct {
	// 全てのクライアントを取得するかどうか.
	All OptBool `json:",omitempty,omitzero"`
}

// GetClipFolderParams is parameters of getClipFolder operation.
type GetClipFolderParams struct {
	// クリップフォルダUUID.
	FolderId uuid.UUID
}

// GetClipsParams is parameters of getClips operation.
type GetClipsParams struct {
	// 取得する件数.
	Limit OptInt `json:",omitempty,omitzero"`
	// 取得するオフセット.
	Offset OptInt `json:",omitempty,omitzero"`
	// 昇順か降順か.
	Order OptOrderInQuery `json:",omitempty,omitzero"`
	// クリップフォルダUUID.
	FolderId uuid.UUID
}

// GetDirectMessagesParams is parameters of getDirectMessages operation.
type GetDirectMessagesParams struct {
	// 取得する件数.
	Limit OptInt `json:",omitempty,omitzero"`
	// 取得するオフセット.
	Offset OptInt `json:",omitempty,omitzero"`
	// 取得する時間範囲の開始日時.
	Since OptDateTime `json:",omitempty,omitzero"`
	// 取得する時間範囲の終了日時.
	Until OptDateTime `json:",omitempty,omitzero"`
	// 範囲の端を含めるかどうか.
	Inclusive OptBool `json:",omitempty,omitzero"`
	// 昇順か降順か.
	Order OptOrderInQuery `json:",omitempty,omitzero"`
	// ユーザーUUID.
	UserId uuid.UUID
}

// GetFileParams is parameters of getFile operation.
type GetFileParams struct {
	// 1を指定するとレスポンスにContent-Dispositionヘッダーが付与されます.
	Dl OptInt `json:",omitempty,omitzero"`
	// ファイルUUID.
	FileId uuid.UUID
}

// GetFileMetaParams is parameters of getFileMeta operation.
type GetFileMetaParams struct {
	// ファイルUUID.
	FileId uuid.UUID
}

// GetFilesParams is parameters of getFiles operation.
type GetFilesParams struct {
	// アップロード先チャンネルUUID.
	ChannelId OptUUID `json:",omitempty,omitzero"`
	// 取得する件数.
	Limit OptInt `json:",omitempty,omitzero"`
	// 取得するオフセット.
	Offset OptInt `json:",omitempty,omitzero"`
	// 取得する時間範囲の開始日時.
	Since OptDateTime `json:",omitempty,omitzero"`
	// 取得する時間範囲の終了日時.
	Until OptDateTime `json:",omitempty,omitzero"`
	// 範囲の端を含めるかどうか.
	Inclusive OptBool `json:",omitempty,omitzero"`
	// 昇順か降順か.
	Order OptOrderInQuery `json:",omitempty,omitzero"`
	// アップロード者が自分のファイルのみを取得するか.
	Mine OptBool `json:",omitempty,omitzero"`
}

// GetLiveKitTokenParams is parameters of getLiveKitToken operation.
type GetLiveKitTokenParams struct {
	// ルームUUID.
	RoomId OptUUID `json:",omitempty,omitzero"`
	// ウェビナールームかどうか(デフォルト false).
	IsWebinar OptBool `json:",omitempty,omitzero"`
}

// GetMessageParams is parameters of getMessage operation.
type GetMessageParams struct {
	// メッセージUUID.
	MessageId uuid.UUID
}

// GetMessageClipsParams is parameters of getMessageClips operation.
type GetMessageClipsParams struct {
	// メッセージUUID.
	MessageId uuid.UUID
}

// GetMessageStampsParams is parameters of getMessageStamps operation.
type GetMessageStampsParams struct {
	// メッセージUUID.
	MessageId uuid.UUID
}

// GetMessagesParams is parameters of getMessages operation.
type GetMessagesParams struct {
	// 取得する件数.
	Limit OptInt `json:",omitempty,omitzero"`
	// 取得するオフセット.
	Offset OptInt `json:",omitempty,omitzero"`
	// 取得する時間範囲の開始日時.
	Since OptDateTime `json:",omitempty,omitzero"`
	// 取得する時間範囲の終了日時.
	Until OptDateTime `json:",omitempty,omitzero"`
	// 範囲の端を含めるかどうか.
	Inclusive OptBool `json:",omitempty,omitzero"`
	// 昇順か降順か.
	Order OptOrderInQuery `json:",omitempty,omitzero"`
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// GetMyQRCodeParams is parameters of getMyQRCode operation.
type GetMyQRCodeParams struct {
	// 画像でなくトークン文字列で返すかどうか.
	Token OptBool `json:",omitempty,omitzero"`
}

// GetMyStampHistoryParams is parameters of getMyStampHistory operation.
type GetMyStampHistoryParams struct {
	// 件数.
	Limit OptInt `json:",omitempty,omitzero"`
}

// GetOAuth2AuthorizeParams is parameters of getOAuth2Authorize operation.
type GetOAuth2AuthorizeParams struct {
	ResponseType        OptOAuth2ResponseType `json:",omitempty,omitzero"`
	ClientID            string
	RedirectURI         OptString       `json:",omitempty,omitzero"`
	Scope               OptString       `json:",omitempty,omitzero"`
	State               OptString       `json:",omitempty,omitzero"`
	CodeChallenge       OptString       `json:",omitempty,omitzero"`
	CodeChallengeMethod OptString       `json:",omitempty,omitzero"`
	Nonce               OptString       `json:",omitempty,omitzero"`
	Prompt              OptOAuth2Prompt `json:",omitempty,omitzero"`
}

// GetOgpParams is parameters of getOgp operation.
type GetOgpParams struct {
	// OGPを取得したいURL.
	URL string
}

// GetPinParams is parameters of getPin operation.
type GetPinParams struct {
	// メッセージUUID.
	MessageId uuid.UUID
}

// GetPublicUserIconParams is parameters of getPublicUserIcon operation.
type GetPublicUserIconParams struct {
	// ユーザー名.
	Username string
}

// GetRoomMetadataParams is parameters of getRoomMetadata operation.
type GetRoomMetadataParams struct {
	// ルームUUID.
	RoomId uuid.UUID
}

// GetStampParams is parameters of getStamp operation.
type GetStampParams struct {
	// スタンプUUID.
	StampId uuid.UUID
}

// GetStampImageParams is parameters of getStampImage operation.
type GetStampImageParams struct {
	// スタンプUUID.
	StampId uuid.UUID
}

// GetStampPaletteParams is parameters of getStampPalette operation.
type GetStampPaletteParams struct {
	// スタンプパレットUUID.
	PaletteId uuid.UUID
}

// GetStampStatsParams is parameters of getStampStats operation.
type GetStampStatsParams struct {
	// スタンプUUID.
	StampId uuid.UUID
}

// GetStampsParams is parameters of getStamps operation.
type GetStampsParams struct {
	// Unicode絵文字を含ませるかどうか
	// Deprecated:
	// typeクエリを指定しなければ全てのスタンプを取得できるため、そちらを利用してください.
	//
	// Deprecated: schema marks this parameter as deprecated.
	IncludeUnicode OptBool `json:",omitempty,omitzero"`
	// 取得するスタンプの種類.
	Type OptGetStampsType `json:",omitempty,omitzero"`
}

// GetTagParams is parameters of getTag operation.
type GetTagParams struct {
	// タグUUID.
	TagId uuid.UUID
}

// GetThumbnailImageParams is parameters of getThumbnailImage operation.
type GetThumbnailImageParams struct {
	// ファイルUUID.
	FileId uuid.UUID
	// 取得するサムネイルのタイプ.
	Type OptThumbnailType `json:",omitempty,omitzero"`
}

// GetUserParams is parameters of getUser operation.
type GetUserParams struct {
	// ユーザーUUID.
	UserId uuid.UUID
}

// GetUserDMChannelParams is parameters of getUserDMChannel operation.
type GetUserDMChannelParams struct {
	UserId uuid.UUID
}

// GetUserGroupParams is parameters of getUserGroup operation.
type GetUserGroupParams struct {
	// ユーザーグループUUID.
	GroupId uuid.UUID
}

// GetUserGroupAdminsParams is parameters of getUserGroupAdmins operation.
type GetUserGroupAdminsParams struct {
	// ユーザーグループUUID.
	GroupId uuid.UUID
}

// GetUserGroupMembersParams is parameters of getUserGroupMembers operation.
type GetUserGroupMembersParams struct {
	// ユーザーグループUUID.
	GroupId uuid.UUID
}

// GetUserIconParams is parameters of getUserIcon operation.
type GetUserIconParams struct {
	// ユーザーUUID.
	UserId uuid.UUID
}

// GetUserStatsParams is parameters of getUserStats operation.
type GetUserStatsParams struct {
	// ユーザーUUID.
	UserId uuid.UUID
}

// GetUserTagsParams is parameters of getUserTags operation.
type GetUserTagsParams struct {
	// ユーザーUUID.
	UserId uuid.UUID
}

// GetUsersParams is parameters of getUsers operation.
type GetUsersParams struct {
	// アカウントがアクティブでないユーザーを含め、全てのユーザーを取得するかどうか.
	IncludeSuspended OptBool `json:",omitempty,omitzero"`
	// 名前が一致するアカウントのみを取得する.
	Name OptString `json:",omitempty,omitzero"`
}

// GetWebhookParams is parameters of getWebhook operation.
type GetWebhookParams struct {
	// WebhookUUID.
	WebhookId uuid.UUID
}

// GetWebhookIconParams is parameters of getWebhookIcon operation.
type GetWebhookIconParams struct {
	// WebhookUUID.
	WebhookId uuid.UUID
}

// GetWebhookMessagesParams is parameters of getWebhookMessages operation.
type GetWebhookMessagesParams struct {
	// 取得する件数.
	Limit OptInt `json:",omitempty,omitzero"`
	// 取得するオフセット.
	Offset OptInt `json:",omitempty,omitzero"`
	// 取得する時間範囲の開始日時.
	Since OptDateTime `json:",omitempty,omitzero"`
	// 取得する時間範囲の終了日時.
	Until OptDateTime `json:",omitempty,omitzero"`
	// 範囲の端を含めるかどうか.
	Inclusive OptBool `json:",omitempty,omitzero"`
	// 昇順か降順か.
	Order OptOrderInQuery `json:",omitempty,omitzero"`
	// WebhookUUID.
	WebhookId uuid.UUID
}

// GetWebhooksParams is parameters of getWebhooks operation.
type GetWebhooksParams struct {
	// 全てのWebhookを取得します。権限が必要です。.
	All OptBool `json:",omitempty,omitzero"`
}

// InactivateBotParams is parameters of inactivateBot operation.
type InactivateBotParams struct {
	// BOTUUID.
	BotId uuid.UUID
}

// LetBotJoinChannelParams is parameters of letBotJoinChannel operation.
type LetBotJoinChannelParams struct {
	// BOTUUID.
	BotId uuid.UUID
}

// LetBotLeaveChannelParams is parameters of letBotLeaveChannel operation.
type LetBotLeaveChannelParams struct {
	// BOTUUID.
	BotId uuid.UUID
}

// LoginParams is parameters of login operation.
type LoginParams struct {
	// リダイレクト先.
	Redirect OptURI `json:",omitempty,omitzero"`
}

// LogoutParams is parameters of logout operation.
type LogoutParams struct {
	// リダイレクト先.
	Redirect OptURI `json:",omitempty,omitzero"`
	// 全てのセッションでログアウトするかどうか.
	All OptBool `json:",omitempty,omitzero"`
}

// PostDirectMessageParams is parameters of postDirectMessage operation.
type PostDirectMessageParams struct {
	// ユーザーUUID.
	UserId uuid.UUID
}

// PostMessageParams is parameters of postMessage operation.
type PostMessageParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// PostWebhookParams is parameters of postWebhook operation.
type PostWebhookParams struct {
	// リクエストボディシグネチャ(Secretが設定されている場合は必須).
	XTRAQSignature OptString `json:",omitempty,omitzero"`
	// 投稿先のチャンネルID(変更する場合).
	XTRAQChannelID OptString `json:",omitempty,omitzero"`
	// メンション・チャンネルリンクを自動埋め込みする場合に1を指定する.
	Embed OptInt `json:",omitempty,omitzero"`
	// WebhookUUID.
	WebhookId uuid.UUID
}

// ReadChannelParams is parameters of readChannel operation.
type ReadChannelParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// ReissueBotParams is parameters of reissueBot operation.
type ReissueBotParams struct {
	// BOTUUID.
	BotId uuid.UUID
}

// RemoveMessageStampParams is parameters of removeMessageStamp operation.
type RemoveMessageStampParams struct {
	// メッセージUUID.
	MessageId uuid.UUID
	// スタンプUUID.
	StampId uuid.UUID
}

// RemoveMyStarParams is parameters of removeMyStar operation.
type RemoveMyStarParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// RemoveMyUserTagParams is parameters of removeMyUserTag operation.
type RemoveMyUserTagParams struct {
	// タグUUID.
	TagId uuid.UUID
}

// RemovePinParams is parameters of removePin operation.
type RemovePinParams struct {
	// メッセージUUID.
	MessageId uuid.UUID
}

// RemoveUserGroupAdminParams is parameters of removeUserGroupAdmin operation.
type RemoveUserGroupAdminParams struct {
	// ユーザーグループUUID.
	GroupId uuid.UUID
	// ユーザーUUID.
	UserId uuid.UUID
}

// RemoveUserGroupMemberParams is parameters of removeUserGroupMember operation.
type RemoveUserGroupMemberParams struct {
	// ユーザーグループUUID.
	GroupId uuid.UUID
	// ユーザーUUID.
	UserId uuid.UUID
}

// RemoveUserGroupMembersParams is parameters of removeUserGroupMembers operation.
type RemoveUserGroupMembersParams struct {
	// ユーザーグループUUID.
	GroupId uuid.UUID
}

// RemoveUserTagParams is parameters of removeUserTag operation.
type RemoveUserTagParams struct {
	// ユーザーUUID.
	UserId uuid.UUID
	// タグUUID.
	TagId uuid.UUID
}

// RevokeClientTokensParams is parameters of revokeClientTokens operation.
type RevokeClientTokensParams struct {
	// OAuth2クライアントUUID.
	ClientId string
}

// RevokeMySessionParams is parameters of revokeMySession operation.
type RevokeMySessionParams struct {
	// セッションUUID.
	SessionId uuid.UUID
}

// RevokeMyTokenParams is parameters of revokeMyToken operation.
type RevokeMyTokenParams struct {
	// OAuth2トークンUUID.
	TokenId uuid.UUID
}

// SearchMessagesParams is parameters of searchMessages operation.
type SearchMessagesParams struct {
	// 検索ワード
	// Simple-Query-String-Syntaxをパースして検索します.
	Word OptString `json:",omitempty,omitzero"`
	// 投稿日時が指定日時より後.
	After OptDateTime `json:",omitempty,omitzero"`
	// 投稿日時が指定日時より前.
	Before OptDateTime `json:",omitempty,omitzero"`
	// メッセージが投稿されたチャンネル.
	In OptUUID `json:",omitempty,omitzero"`
	// メンションされたユーザー.
	To []uuid.UUID `json:",omitempty"`
	// メッセージを投稿したユーザー.
	From []uuid.UUID `json:",omitempty"`
	// 引用しているメッセージ.
	Citation OptUUID `json:",omitempty,omitzero"`
	// メッセージを投稿したユーザーがBotかどうか.
	Bot OptBool `json:",omitempty,omitzero"`
	// メッセージがURLを含むか.
	HasURL OptBool `json:",omitempty,omitzero"`
	// メッセージが添付ファイルを含むか.
	HasAttachments OptBool `json:",omitempty,omitzero"`
	// メッセージが画像を含むか.
	HasImage OptBool `json:",omitempty,omitzero"`
	// メッセージが動画を含むか.
	HasVideo OptBool `json:",omitempty,omitzero"`
	// メッセージが音声ファイルを含むか.
	HasAudio OptBool `json:",omitempty,omitzero"`
	// 検索結果から取得するメッセージの最大件数.
	Limit OptInt `json:",omitempty,omitzero"`
	// 検索結果から取得するメッセージのオフセット.
	Offset OptInt `json:",omitempty,omitzero"`
	// ソート順 (作成日時が新しい `createdAt`, 作成日時が古い `-createdAt`,
	// 更新日時が新しい `updatedAt`, 更新日時が古い `-updatedAt`).
	Sort OptSearchMessagesSort `json:",omitempty,omitzero"`
}

// SetChannelSubscribeLevelParams is parameters of setChannelSubscribeLevel operation.
type SetChannelSubscribeLevelParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// SetChannelSubscribersParams is parameters of setChannelSubscribers operation.
type SetChannelSubscribersParams struct {
	// チャンネルUUID.
	ChannelId uuid.UUID
}

// UnclipMessageParams is parameters of unclipMessage operation.
type UnclipMessageParams struct {
	// クリップフォルダUUID.
	FolderId uuid.UUID
	// メッセージUUID.
	MessageId uuid.UUID
}

// UpdateRoomMetadataParams is parameters of updateRoomMetadata operation.
type UpdateRoomMetadataParams struct {
	// ルームUUID.
	RoomId uuid.UUID
}
